name: Push packages to NuGet
on:
  push:
    branches:
      - master
    tags:
      - v*
        
jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.102
      - name: Create packages
        run: sudo bash fake.sh -t "Create NuGet packages"
      - name: Push packages
        run: dotnet push Fugit.*.nupkg -s https://api.nuget.org/v3/index.json -k "$NUGET_KEY"
        working-directory: NuGet
        env: 
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
