name: Push packages to NuGet
on:
  push:
    branches:
      - master
    tags:
      - v*
        
jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET SDK 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.*'
      - name: Setup .NET SDK 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.*'
      - name: Create packages
        run: bash fake.sh build -t Deploy
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
