name: Run tests
on:
  push:
    paths:
      - src/**
      - tests/**
    tags-ignore:
      - '**'
  pull_request:
    paths:
      - src/**
      - tests/**
    tags-ignore:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET SDK 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.*'
     - name: Setup .NET SDK 3.1
       uses: actions/setup-dotnet@v1
       with:
         dotnet-version: '3.1.*'
      - name: Run tests
        run: bash fake.sh build -t All
